### ISSUE TITLE
File not found

### ISSUE THREAD

**Issue by geshpoyo** [blackears/parrotLipsync#1] opened 2024-02-28 09:04 UTC
I am getting an error message. In the meantime, the installation itself was finished and WhisperLib was downloaded correctly in Console. I'm stuck here in the video tutorial and need help.
![image](https://github.com/blackears/parrotLipsync/assets/161577015/49f48551-36cb-474b-9f41-4bca4521bce7)

The error message provided indicates an issue with running an external program using the subprocess module in Python?
What should I do?I thought the error might be due to Japanese strings in the file path, so I tried putting the file in C\tem\ but that didn't help.

I created a new account and posted here, but I sent the same information to BlenderMarket.Sorry for double posting.

Also, can I use double-byte characters in Japanese and other Asian languages? I am planning to create a PhonemeGroup for Japanese, but for the time being I used Whisper translated into English by EN.

I also made a LIP POSE in another video and I followed it, but in the video it looked like I was creating actions in the action editor. I am under the impression that I can create an animation using only POSE with auto-completion, but am I wrong?

**Comment by blackears** [comment] 2024-02-28 12:15
I'm not sure.  It looks like it's having trouble loading the audio file, so make sure FFMpeg is set up and that it can be found from the command line.  It could also be due to characters in the file path that it cannot handle - you might want to test with a path that contains only western characters if you haven't already.  Are you able to use Parrot on the example files that come with the project?

I do not read Asian languages and did not test with them.  I would expect that using unicode characters would be fine, but I cannot confirm that.

I'm not sure what you mean by creating poses using auto completion.  Parrot works by taking poses (ie, one frame action animations) from the source action and combining them into a single lipsync action.  (The NLA button does the same thing, but with extra work that then inserts the action into the correct place in your timeline.)  The pose library can be a useful way to organize your mouth poses, but is not strictly necessary.  Parrot just cares that you've added the pose actions to the phoneme table section so that it can find them.

**Comment by blackears** [comment] 2024-02-28 18:06
I've done some investigation.  The other main phonemizing package called Phonemizer doesn't seem to handle Japanese characters either.  (At least, the eSpeak-ng backend is reporting that it does not support 'ja').  I'm afraid I don't know how of any publicly available libraries that I can use to turn Japanese words into syllables.

**Comment by geshpoyo** [comment] 2024-02-29 01:05
Hi Blackear, thanks for looking into all this.
I checked the version from the command line, and it seems that the Path is working, and in fact, I can use Whisper to recognize speech using this FFMPEG, even if I use Whisper alone, but in Japanese, Chinese, and Korean, which are languages that use 2-byte characters, so I'm not sure if anyone else will have the same problem in the future. Someone else may have the same problem.

I have tried various add-ons, but the ones that use external programs, I can't tell at what stage the problem is happening, and Parrot can't tell at what stage the problem is happening, so what I suggested is a system that can check if FFMPEG, Gruut, and Whisper can be used properly from the add-ons（Chekin system）.

 I would like to have a system that can check if FFMPEG, Gruut and Whisper are working properly from Addon.
![image](https://github.com/blackears/parrotLipsync/assets/161577015/e3f597f9-aa0c-4530-9ce7-3aed1ae160dc)
If most of the stages where problems are occurring are in this installation stage, it is a bit difficult for the average user to relay Blender and check by themselves in Python, so please consider this.
As attached in the image, I found the string "Application" in Japanese in the FFMEG path, so I will install this in a different location today and report back with the results.

By using Unicode characters, do you mean that Blender can convert Unicode8 and Unicode16?




> I have not tested it because I cannot read Asian languages. I think if you use Unicode characters it should be fine, but I can't confirm that.
> 
> I'm not sure what you mean by using auto-completion to create pauses; Parrot works by taking pauses (i.e. one frame of action animation) from the source action and combining them into a single lip-sync action. (The NLA button does the same thing, but requires additional work to insert the action at the correct position in the timeline.
> additional work to insert the action at the correct position in the timeline). The Pose Library is useful for organizing mouth poses, but is not strictly necessary; Parrot only cares if you are adding pause actions to sections of the phoneme table.

And sorry for the confusion, I meant Interpolation, not AutoCompletion. I understood that you use the Pose library as a keyframe and register the keyframe in the Phoneme Table.
I would be happy to check if I am actually registering the MouthPose correctly from the Phoneme Table, and from what I hear from Blackear, I think my understanding is probably correct.

I see that Gruut does not support Japanese. Thanks for letting me know. It would be nice to have the ability to semi-automatically add KeyFrames to Parrot in Japanese.
For example, English is of course available in Parrot, but Japanese is not as complex with vowels and consonants as English. In Japanese, there is the vowel A, but in English, there are different ways to use it, such as EA, A, OA, etc. In addition, the sound of air friction from the teeth, such as THINK (θink), can be expressed with only S in Japanese. As I mentioned in a comment on Youtube, it would be nice to add a marker for languages that are not currently supported by Gruut, so that vowels and consonants are added to the marker and can be edited. I would be very happy if it were possible to keystroke in a relative amount of time.
It's a pity that there is no conversion library for Asian languages, but if we can make KeyFrames from Whisper's SRT files by referring to the Phoneme Table without using Gruut in the end, we may be able to use any language.

Suppose you read an SRT file written in Japanese.
```
1
00:00:00,000 --> 00:00:02,000
やあ（YAA）、Blackear(burakku iyaa)（Hi BlackEar）

2
00:00:05,000 --> 00:00:08,000
元気かい（genki kai）？（How you doing?）
```

I think you can use PoseLIB to type A and YA as keyframes for YAA, etc. in the string.

That's all I have to offer, sorry for the length.Have a nice day!

**Comment by blackears** [comment] 2024-02-29 03:05
I don't think the problem is using 2 bytes characters specifically.  However, Whisper is treating east Asian languages differently than phonetic languages.  I tried this on some Japanese dialog and got back a completely different data format.  Which is not a problem by itself, but I then need a way to then decode those characters.  The symbols that whisper is returning don't display on my screen, so I don't know if they are kanji or hiragana.  If they are hiragana, I might be able to translate them to mouth poses, but if they are kanji it is going to require a large dictionary to be able to do that.

At the moment whisper is set up to return words rather than syllables.  There is a thread from 2022 on their forum where they discuss using the international phonetic alphabet, but I don't think it's ever been implemented.  So for phonetic languages, I get a list of words and timings from Whisper and then send the word to a program that can break them down into syllables.  For Japanese, though, it's giving me something more like entire sentences.  I could work with this, except neither Gruut nor Phonemizer seem to work with east Asian languages.  Phonemizer claims to, but when I try to use it, it says it can't find the symbols it needs.  I did see that Gruut has a partial implementation for Korean.  You might want to check their website to see if they have a project underway for supporting Japanese.  (They seem to be using [voice2json](https://github.com/synesthesiam/voice2json?tab=readme-ov-file) as a source, and voice2json mentions project [Julius](https://github.com/julius-speech/julius) at Kyoto university as a source, so maybe there is something going on).

I tried to set up Parrot to automatically install the necessary addons, but I was unable to get it to work.  Unfortunately, AI programs are still very new and require a lot of special attention to get them to work.  I've not found any simpler way to get things to install that work for most environments.  Hopefully things will become simpler at the technology evolves.

**Comment by geshpoyo** [comment] 2024-02-29 03:46
I reinstalled FFMPEG again at the following location.
![image](https://github.com/blackears/parrotLipsync/assets/161577015/b913e945-fd0e-4c3e-8df4-9bcad9759997)
![image](https://github.com/blackears/parrotLipsync/assets/161577015/c6d4255c-223f-4d6d-93b2-1b0939f811f4)

But same error occur ,hmm
![image](https://github.com/blackears/parrotLipsync/assets/161577015/220655af-7ad8-47ed-b9c9-6319ce1b452d)

By the way , I am using the English version in Blender, but the Console returns an error in Japanese at the end of the sentence.

`FileNotFoundError: [WinError 2] 指定されたファイルが見つかりません。. (The specified file cannot be found.).`

I used the mp3 file you provided for the audio file. By the way, I know that Whisper recognizes Wav, but what other file formats are supported?

I think the installation itself was successful, but I don't know what I should do from this error, so I would like to know.


I see that there is currently no project that supports Japanese. I see that Kyoto University has an interesting project, and I am looking forward to seeing it in the future.

By the way, if you can read SRT files, you can use word by word to transcribe not words, but words that are pronounced by the transcriber. For example, with Whisper
For example, if you use Whisper to transcribe the sentence "今日は暑いですねToday is so hot, isn't it?
So, the string "今日は暑いですね→**きょう**は**あつ**いですねToday is so hot." can be converted into hiragana only. Therefore, there is no need for a dictionary to recognize Kanji characters. Since there are many ways to read kanji, the problem can be solved with Workaround, which converts kanji to hiragana from the beginning in order to make the kanji be read in different ways.


Automatic installation seems to be difficult. However, it would be helpful if Parrot could check to see if we are in an environment where the necessary programs can be executed correctly.

**Comment by blackears** [comment] 2024-02-29 04:35
I'm not sure why you're getting that error. It looks like ffmpeg is installed correctly.  And I was able to get past this point when I tested using Japanese on my system.  My only guess is something is wrong with the file path.  What is the path your file is stored at?

Whisper uses ffmpeg for reading the audio.  Ffmpeg can handle most common audio formats like mp3, ogg, wav, au and others.

The plugin doesn't use SRT files, but does get similar data from the Python API.

If you know of a way to convert kanji to hiragana, Parrot could work with that.  I don't know where I could find that, though.  I'm not sure if Whisper is returning kanji or hiragana, but if it is kanji, there will need to be some way to convert it.

I can put in checks for `whisper_timestamped` and `gruut`, but I'm not sure how I'd test for ffmpeg.

**Comment by geshpoyo** [comment] 2024-02-29 13:25
I'll test blender once in a clean environment, though it will take me a while to test things at work. I'll report back when I have more results.Maybe Ill try to use portable ver.

**Comment by geshpoyo** [comment] 2024-03-01 09:07
Hi, I've been doing a lot of testing between jobs, and I've concluded that even with a clean Blender installation and no non-Parrot addons, unfortunately we get the same error in our environment.

I have one question, there is a command in Blendermarket for Gruut and Whisper to Updatre, but why is it Update if I didn't install it in the first place? Maybe this command automatically installs Gruut and Whisper if they are not there. what is numpy for?

. /python.exe -m pip install --upgrade numpy
. /python.exe -m pip install --upgrade whisper_timestamped
. /python.exe -m pip install --upgrade gruut

I'm sorry, but can you please refund my Parrot purchase on BlenderMarket until someone says Parrot is a little more stable and usable?

**Comment by blackears** [comment] 2024-03-02 13:35
I think you can get a refund by contacting Blender Market.  Or there might be a button on your order page.  Let me know if this is not the case.

You can still get the addon from the Github page regardless.  I'm not really sure what's going wrong with your installation and I can't really test it.

`numpy` is a general purpose computation package that is used by a large number of Python modules including Whisper.  It's included here so you upgrade to the latest version.  The `--upgrade` flag will install a package even if it is not already installed.

Whisper and Gruut do not seem to support east Asian languages well.  Hopefully this will change in the future and the addon can be more general purpose.

**Comment by blackears** [comment] 2024-03-11 18:04
Closing this.  Let me know if you're still having problems.

**Closed by blackears** 2024-03-11 18:04 UTC
